export const cplRequirements = [
  {
    id: 'total-flight-time',
    code: 'CPL-01',
    name: 'Total Flight Time as Pilot of Aeroplane for CPL(A)',
    category: 'cumulative',
    requiredValue: 200 * 60,
    unit: 'hours',
    calculationType: 'sum-duration',
    lookbackPeriod: null,
    requiresValidity: false,
    validityMonths: null,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'This is the cumulative flight time requirement for CPL(A). All valid student flight logs contribute toward the total once the record is approved.'
  },
  {
    id: 'pic-time',
    code: 'CPL-02',
    name: 'Flight Time as PIC',
    category: 'cumulative',
    requiredValue: 100 * 60,
    unit: 'hours',
    calculationType: 'sum-pic',
    lookbackPeriod: null,
    requiresValidity: false,
    validityMonths: null,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'Only qualifying PIC or solo flight time is counted. Dual flights are not included in this cumulative PIC total.'
  },
  {
    id: 'pic-recent',
    code: 'CPL-03',
    name: 'PIC Flight Time within applicable recent-period requirement',
    category: 'recent',
    requiredValue: 100 * 60,
    unit: 'hours',
    calculationType: 'sum-recent-pic',
    lookbackPeriod: 6,
    requiresValidity: true,
    validityMonths: 6,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'This requirement is based on the applicable 6-month recent-flight period. Older flights are still visible in history but are not counted toward the current qualifying value.'
  },
  {
    id: 'cross-country-pic',
    code: 'CPL-04',
    name: 'Cross Country Flight Time as PIC',
    category: 'cumulative',
    requiredValue: 20 * 60,
    unit: 'hours',
    calculationType: 'sum-cross-country-pic',
    lookbackPeriod: null,
    requiresValidity: false,
    validityMonths: null,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'Cross-country time is counted when the flight is logged as PIC and the journey meets the qualifying cross-country criteria.'
  },
  {
    id: 'cross-country-distance',
    code: 'CPL-05',
    name: 'Cross Country Flight Distance',
    category: 'cumulative',
    requiredValue: 300,
    unit: 'nm',
    calculationType: 'sum-distance',
    lookbackPeriod: null,
    requiresValidity: false,
    validityMonths: null,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'Total qualifying cross-country distance is calculated from student flight records marked as cross-country and approved for CPL progress tracking.'
  },
  {
    id: 'instrument-time',
    code: 'CPL-06',
    name: 'Instrument Time',
    category: 'cumulative',
    requiredValue: 10 * 60,
    unit: 'hours',
    calculationType: 'sum-instrument',
    lookbackPeriod: null,
    requiresValidity: false,
    validityMonths: null,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'Instrument time contributes when it is logged as applicable instrument flying and meets the approved training criteria.'
  },
  {
    id: 'instrument-aircraft',
    code: 'CPL-07',
    name: 'Instrument Time on Aircraft',
    category: 'cumulative',
    requiredValue: 5 * 60,
    unit: 'hours',
    calculationType: 'sum-instrument-aircraft',
    lookbackPeriod: null,
    requiresValidity: false,
    validityMonths: null,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'Instrument time on aircraft is counted separately from general instrument training and must be logged on an approved training aircraft.'
  },
  {
    id: 'night-pic',
    code: 'CPL-08',
    name: 'Night Flight Time as PIC',
    category: 'recent',
    requiredValue: 5 * 60,
    unit: 'hours',
    calculationType: 'sum-night-pic',
    lookbackPeriod: 6,
    requiresValidity: true,
    validityMonths: 6,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'This requirement is based on the applicable recent night-flight period. Only night flights within the qualifying window count toward the current requirement.'
  },
  {
    id: 'night-takeoffs',
    code: 'CPL-09',
    name: 'Night Take-offs',
    category: 'recent',
    requiredValue: 10,
    unit: 'count',
    calculationType: 'sum-count',
    lookbackPeriod: 6,
    requiresValidity: true,
    validityMonths: 6,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'Night take-offs are counted from qualifying night flights logged within the applicable recent period. Older night take-offs are archived in the flight history.'
  },
  {
    id: 'night-landings',
    code: 'CPL-10',
    name: 'Night Landings',
    category: 'recent',
    requiredValue: 10,
    unit: 'count',
    calculationType: 'sum-count',
    lookbackPeriod: 6,
    requiresValidity: true,
    validityMonths: 6,
    warningDays: 30,
    source: 'DGCA CAR',
    sourceRevision: 'Current Revision',
    sourceDate: '2026-01-01',
    active: true,
    note: 'Night landings are counted from qualifying night flights within the recent experience window. This helps confirm the student is current for night operations.'
  }
]
